### PR TITLE
musdb18 errata

### PR DESCRIPTION
**Pull request by faroit**
@TE-StefanUhlich can you list the other errata items here, please?

### CODE REVIEW

**Comment by TE-StefanUhlich** [comment]
@faroit Here are more items for the errata list:

| Track                   | Position | Error                               |
| ----------------------- | -------- | ----------------------------------- |
| Hop Along - Sister Cities     |      | bleeding of other instruments into vocals |
| Chris Durban - Celebrate |     | bleeding of other instruments into vocals |
| Leaf - Wicked         | 3:02 - 3:08 | guitar mixed into vocals |

**Comment by KimberleyJensen** [comment]
Track - Detsky Sad - Walkie Talkie 
Error - other mixed into drums

This one is from the test set

**Comment by faroit** [comment]
Thanks @KimberleyJensen @TE-StefanUhlich will merge this in then and publicly announce. We may need to do a new version at one point

**Comment by faroit** [comment]
Also 

# PR - Oh No

sum of sources does not add up to the mix for the left channel

**Pull request merged**
